server:
  port: 8900
spring:
  application:
    name: consumer-order
user:
  url: http://localhost:7900/user/
eureka:
  instance:
    prefer-ip-address: true #使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #在控制台显示ip
  client:
    service-url:
      defaultZone: http://user:123@localhost:9900/eureka