server:
  port: 8902
spring:
  application:
    name: consumer-order-hystrix
user:
  url: http://localhost:7900/user/
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://user:123@localhost:9900/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"